#!/command/with-contenv sh
groupmod -g \${PGID} deluge || addgroup -g \${PGID} -S deluge
usermod -u \${PUID} -g \${PGID} deluge || adduser -u \${PUID} -G deluge -S deluge
mkdir -p \${DELUGE_CONFIG_DIR} \${DELUGE_DOWNLOAD_DIR}
chown -R deluge:deluge \${DELUGE_CONFIG_DIR} \${DELUGE_DOWNLOAD_DIR}
