#!/command/with-contenv sh
CONFIG_DIR=${CONFIG_DIR:-/config}
if [ "$PUID" -eq 0 ] || [ "$PGID" -eq 0 ]; then
	exec deluged -d -c "$CONFIG_DIR" -L info 2>&1
else 
	exec s6-setuidgid deluge deluged -d -c "$CONFIG_DIR" -L info 2>&1
fi
